# Generated by Django 5.1.2 on 2024-12-30 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpricing',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_pricing', to='pricing.sport'),
        ),
        migrations.AlterField(
            model_name='pricingoverride',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_overrides', to='pricing.sport'),
        ),
    ]
