# Generated by Django 5.1.2 on 2024-12-30 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_defaultpricing_sport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpricing',
            name='sport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_pricing', to='pricing.sport'),
        ),
    ]
