# Generated by Django 5.1.2 on 2024-12-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_defaultpricing_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingoverride',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pricingoverride',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
    ]
