# Generated by Django 5.1.2 on 2024-12-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_pricingoverride_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingoverride',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingoverride',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
