# Generated by Django 5.1.2 on 2024-12-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_pricingoverride_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
